version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: taskmanager-db
    restart: always
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: task123
      POSTGRES_DB: taskmanagerdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
