version: '3.8'

services:
  taskmanager-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5093:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=taskmanagerdb;Username=taskuser;Password=task123
    depends_on:
      - postgres
    networks:
      - taskmanager-network

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=taskuser
      - POSTGRES_PASSWORD=task123
      - POSTGRES_DB=taskmanagerdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - taskmanager-network

networks:
  taskmanager-network:
    driver: bridge

volumes:
  postgres-data: